# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerAppsToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerAppsExportSolution@0
  inputs:
    authenticationType: 'PowerAppsEnvironment'
    PowerAppsEnvironment: 'BAC-DEV2'
    SolutionName: '$(SolutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
- task: PowerAppsUnpackSolution@0
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\\$(SolutionName).zip'
    SolutionTargetFolder: 'CdsConfig'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'buildToPipeline'
    publishLocation: 'pipeline'

- task: CmdLine@2
  inputs:
    script: |
      echo commit all changes
      git config user.email "bcolburn@bcolburn.onmicrosoft.com"
      git config user.name "Automated Build"
      git checkout master
      git add --all
      git commit -m "solution init"
      echo push code to new repo
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master